org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dorg.gradle.internal.instrumentation.agent=false -Dorg.gradle.cache.transforms.immutable=false
org.gradle.vfs.watch=false
org.gradle.parallel=false
org.gradle.java.home=C:\\Users\\Administrator\\.jdks\\openjdk-18.0.1.1
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
