#!/bin/bash
# Setup script for English Reader app
# Downloads pre-built native libraries and model files

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
JNILIBS_DIR="$PROJECT_DIR/app/src/main/jniLibs/arm64-v8a"
MNN_INCLUDE_DIR="$PROJECT_DIR/app/src/main/cpp/mnn-include"

echo "=== English Reader Environment Setup ==="

# Create directories
mkdir -p "$JNILIBS_DIR"
mkdir -p "$MNN_INCLUDE_DIR"

echo ""
echo "1. Native Libraries"
echo "   Place the following .so files in: $JNILIBS_DIR"
echo ""
echo "   llama.cpp (build from https://github.com/ggml-org/llama.cpp):"
echo "     - libggml-base.so"
echo "     - libggml-cpu.so"
echo "     - libggml.so"
echo "     - libllama.so"
echo "     - libomp.so"
echo ""
echo "   MNN (build from https://github.com/alibaba/MNN with -DMNN_BUILD_LLM=ON):"
echo "     - libMNN.so"
echo "     - libMNN_CL.so"
echo "     - libMNN_Express.so"
echo "     - libMNNOpenCV.so"
echo "     - libdiffusion.so"
echo "     - libllm.so"
echo ""
echo "   Build commands (on Linux with Android NDK):"
echo ""
echo "   # llama.cpp"
echo "   cmake -B build-android -DCMAKE_TOOLCHAIN_FILE=\$NDK/build/cmake/android.toolchain.cmake \\"
echo "     -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-28 \\"
echo "     -DGGML_OPENMP=ON -DBUILD_SHARED_LIBS=ON"
echo "   cmake --build build-android --config Release"
echo ""
echo "   # MNN"
echo "   cmake -B build-android -DCMAKE_TOOLCHAIN_FILE=\$NDK/build/cmake/android.toolchain.cmake \\"
echo "     -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-28 \\"
echo "     -DMNN_BUILD_LLM=ON -DMNN_OPENCL=ON -DMNN_BUILD_DIFFUSION=ON \\"
echo "     -DMNN_SEP_BUILD=OFF -DBUILD_SHARED_LIBS=ON"
echo "   cmake --build build-android --config Release"
echo ""
echo "2. MNN Headers"
echo "   Copy MNN include headers to: $MNN_INCLUDE_DIR"
echo "   Required: MNN/*.hpp, MNN/expr/*.hpp, diffusion/diffusion.hpp"
echo ""
echo "3. Model File"
echo "   Download Qwen3-4B-Q4_K_M.gguf and push to device:"
echo "   adb push Qwen3-4B-Q4_K_M.gguf /data/local/tmp/"
echo ""
echo "   Or place in app internal storage:"
echo "   adb push Qwen3-4B-Q4_K_M.gguf /data/data/com.example.englishreader/files/models/"
echo ""
echo "=== Setup complete ==="
